@startuml
'https://plantuml.com/sequence-diagram

actor Teacher as Actor
participant CreateRegularExamUI as UI <<presentation>>
participant CreateRegularExamController as controller <<application>>
participant PersistenceContext as persistence <<persistence>>
participant RepositoryFactory as factory <<factory>>

Actor -> UI : create regular exam

activate UI

    UI -> controller : create
    activate controller
        controller -> persistence : repositories()
        activate persistence
            persistence -> factory : create
            activate factory
            persistence -> controller : factory
            deactivate factory
        deactivate persistence



    deactivate controller



deactivate UI



@enduml