@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
skinparam padding 2
skinparam ranksep 100
skinparam classFontSize 18


interface MessageProtocol
interface BoardParticipantRepository
{
    +withPermission(SystemUser user, BoardParticipantPermissions perm)
}

class CreatePostItUI
{
    -chooseFile()
}

class CreatePostItController
{
 +isCellIdValid(String arr, int numRows, int numColumns)
 +canCreatePostIt()
 +getBoardsList()
 +createPostIt(String str)
 +createBoardPositionTextString(String boardChosen, String position, String text)
}

class CreatePostItHandler
{
    +run()
    -checkIfCellIsOccupied(Board board, String alterPosition)
    -getStringBuilder()
    -checkIfAllCellsAreOccupied(Board board)
}

class SBProtocol
{
 + setCode(int code)
 + setContentFromString(String cStr)
 + send(DataOutputStream out)
 + getContentAsString()
}

class MenuRequest
{
    +run()
}

class SBPServerApp
{
    +{static}Map<InetAddress, Client> activeAuths
    +{static}Map<BoardTitle, Board> boards
}

class SBPClientAPP
{
}


class CreatePostIt
{
  +parseStr(String content)
}

class Client
{
    +getUserLoggedIn()
}


class BoardService
{
    +boardsUserCanWrite(SystemUser owner)
}

class MainMenu
{
    - buildMainMenu()
}

class PostItService
{
    +createPostIt(Board board, int row, int col, String text, SystemUser postItOwner)
}

class Board
{
   +getCell(int row, int column)
}

class Cell
{
    +addPostIt(PostIt postIt)
}

class PostIt {
}

abstract class BoardHistory
{
}






'extends --|>

CreatePostIt --|> BoardHistory



'depends on(imports)  -->
CreatePostItUI --> "1" CreatePostItController
CreatePostItController --> "*" SBProtocol


CreatePostItHandler --> "*" SBProtocol


CreatePostItHandler --> "1" CreatePostIt
CreatePostItHandler --> "1" Client
CreatePostItHandler --> "1" BoardService
CreatePostItHandler --> "1" PostItService

SBPClientAPP --> "1" MainMenu
MainMenu --> "1" CreatePostItUI
SBPServerApp --> "1" MenuRequest
MenuRequest --> "1" CreatePostItHandler
MenuRequest -up-> "1" SBProtocol

PostItService --> "1" Board
Board --> "*" Cell
Cell --> "1" PostIt

BoardService --> "1" BoardParticipantRepository

SBPServerApp ----> "*" Board
SBPServerApp -> "*" BoardHistory

'implements ..|>
SBProtocol ..|> MessageProtocol

@enduml