rem generated by chat-gpt
rem use at your own risk

@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%" || exit /b 1

set "DEST=..\src\main\resources\static"
set "SRC=.\dist"

set "TEMPLATES=..\src\main\resources\templates"

call npm run build || exit /b 1

echo.

if exist "%DEST%" rd /s /q "%DEST%"

echo.

xcopy /e /i "%SRC%" "%DEST%"

REM HACK: application.properties isn't being read for some reason
md "%TEMPLATES%" 2>nul
move /y "%DEST%\index.html" "%TEMPLATES%"

endlocal
