rem generated by chat-gpt
rem use at your own risk

@echo off
setlocal

cd /d "%~dp0" || exit /b 1

set "DEST=..\src\main\resources\static"
set "SRC=.\dist"

set "TEMPLATES=..\src\main\resources\templates"

npm run build || exit /b 1

echo.

if exist "%DEST%" rd /s /q "%DEST%"

echo.

xcopy /s /e /i "%SRC%" "%DEST%"

rem HACK: application.properties isn't being read for some reason
mkdir "%TEMPLATES%" 2>nul
move /y "%DEST%\index.html" "%TEMPLATES%"

endlocal
