    @startuml

  skinparam linetype ortho
  skinparam Shadowing False

  skinparam class {
        BackgroundColor<<Entity>> Moccasin
        BackgroundColor<<value object>> Azure
        BackgroundColor<<Event>> MediumAquaMarine
        BackgroundColor<<Service>> SkyBlue
        ArrowColor DarkSlateGrey
    }

    skinparam package {
        BackgroundColor PowderBlue
        packageLayout grid
        packageColumn 2
    }

  package TEACHER <<Aggregate>> {
      entity Teacher <<root>> <<Entity>>

      class Acronym <<value object>> 

      class TeacherFullName <<value object>> 

      class TeacherShortName <<value object>> 

      class TeacherDateOfBirth <<value object>> 

      class TeacherTaxPayerNumber <<value object>> 

  Teacher "1" -down--> "1" Acronym
  Teacher "1" -down--> "1" TeacherFullName
  Teacher "1" -up-> "1" TeacherShortName
  Teacher "1" -up-> "1" TeacherDateOfBirth
  Teacher "1" -> "1" TeacherTaxPayerNumber

  }

  package MANAGER <<Aggregate>> {
      entity Manager <<root>> <<Entity>>

      class ManagerId <<value object>> 

      class ManagerFullName <<value object>> 

      class ManagerShortName <<value object>> 

      class ManagerDateOfBirth <<value object>> 

      class ManagerTaxPayerNumber <<value object>> 

      Manager "1" -down--> "1" ManagerId
      Manager "1" -down--> "1" ManagerFullName
      Manager "1" -up-> "1" ManagerShortName
      Manager "1" -up-> "1" ManagerDateOfBirth
      Manager "1" -> "1" ManagerTaxPayerNumber
  }

  package STUDENT <<Aggregate>> {
      entity Student <<root>> <<Entity>>

      class MecanographicNumber <<value object>> 

      class StudentFullName <<value object>> 

      class StudentShortName <<value object>> 

      class StudentDateOfBirth <<value object>> 

      class StudentTaxPayerNumber <<value object>> 

      Student "1" -down--> "1" MecanographicNumber
      Student "1" ---> "1" StudentFullName
      Student "1" -up-> "1" StudentShortName
      Student "1" -up--> "1" StudentDateOfBirth
      Student "1" -> "1" StudentTaxPayerNumber
  }

      package TIMETABLE <<Aggregate>> {
          interface Event <<interface>>

          entity RecurringPattern <<root>> <<entity>>{
              - startDate
              - endDate
              - startTime
              - endTime
          }

          enum RecurringFrequency <<enum>>{
            - weekly
            - once
          }

          RecurringPattern "1" --> "1" RecurringFrequency
          RecurringPattern "1" -> "*" Event
      }

  package CoursePackage <<Rectangle>> {
      package COURSE <<Aggregate>> {
          entity Course <<root>> <<Entity>>

          class CourseCode <<value object>>

          class CourseName <<value object>>

          class CourseDescription <<value object>>

          class CourseClass <<value object>>

          enum CourseState <<value object>>{
              - closed
              - open
              - enroll
              - inProgress
          }

          class CourseCapacity <<value object>> {
              -minStudents
              -maxStudents
          }

          class CourseEvent <<Event>>

          class CourseClosedEvent
          class CourseOpenEvent
          class CourseEnrollOpenEvent
          class CourseEnrollClosedEvent
          class CourseCreatedEvent

          Course "1" -down--> "1" CourseCode
          Course "1" -down--> "1" CourseName
          Course "1" -down--> "1" CourseState
          Course "1" -down--> "1" CourseDescription
          Course "1" -down--> "1" CourseCapacity
          Course -up-> CourseEvent
          Course "1" ----> "*" CourseClass
          CourseEvent -up--> CourseClosedEvent
          CourseEvent -up--> CourseOpenEvent
          CourseEvent -up--> CourseEnrollOpenEvent
          CourseEvent -up--> CourseEnrollClosedEvent
          CourseEvent -up--> CourseCreatedEvent
          CourseClass -up-|> Event
      }

      package COURSE_ACCESS <<Aggreggate>>{
          entity CourseAccess <<root>> <<Entity>>
          CourseAccess "*" -down----> "1" Student
          Course "1" -> "*" CourseAccess

          class CourseEnrollmentRequestEvent <<Event>>
          CourseAccess "1" <-up- "1" CourseEnrollmentRequestEvent
          Manager "1" -down-----> "1" CourseEnrollmentRequestEvent
      }

      Teacher "*" -up> "1" Course : participate >
      'Teacher "1" -> "1" Course : in charge of >
  }

  package ExamPackage <<Rectangle>> {
      package EXAM_SPECIFICATION <<Aggregate>> {
          entity ExamSpecification <<root>> <<Entity>>
          class ExamTitle <<value object>>
          class HeaderDescription <<value object>>
          class ExamHeader <<value object>>
          class ExamSection <<value object>>
          class SectionDescription <<value object>>

          class Question <<value object>> {
              -description
              -solution
          }

          class QuestionFeedback <<value object>>

          enum QuestionType <<value object>> {
              - matching
              - multipleChoices
              - shortAnswer
              - numerical
              - selectMissingWord
              - true/False
          }

          enum FeedbackType <<value object>> {
              - none
              - onSubmission
              - afterClosing
          }

          enum GradeType <<value object>> {
              - none
              - onSubmission
              - afterClosing
          }
      }

      package EXAM <<Aggregate>> {
          entity Exam <<root>> <<Entity>>

          class ExamDate <<value object>> {
              -openDate
              -closeDate
          }

          class ExamEvent <<Event>>
          class OpeningEvent <<Event>>
          class ClosingEvent <<Event>>
      }

      package EXAM_RESULT <<Aggregate>> {
          entity ExamResult <<root>> <<Entity>>

          class ExamGrade <<value object>>
          class ExamFeedback <<value object>>
      }

      class ExamGradingService <<Service>>

      ExamSpecification "1" -up-> "1" ExamTitle
      ExamSpecification "1" -right--> "1" ExamHeader

      ExamHeader "1" -right--> "0..1" HeaderDescription
      ExamHeader "1" -down-> "1" FeedbackType
      ExamHeader "1" -down-> "1" GradeType

      ExamSpecification "1" -up-> "1..*" ExamSection

      ExamSection "1" -up-> "0..1" SectionDescription
      ExamSection "1" -up--> "1..*" Question

      Question "1" -up> "1" QuestionType
      Question "1" -> "0..*" QuestionFeedback

      Exam "1" -down> "1" ExamSpecification
      /' curso liga se a exame '/
      Exam "1" -> "1" ExamDate
      OpeningEvent -up--> ExamEvent
      ClosingEvent -up--> ExamEvent
      Exam "1" -up-> "1" ExamEvent
      ExamGradingService "1" -up----> "1" ExamResult

      ExamResult "1" -up-> "1" ExamGrade
      ExamResult "1" -> "1" ExamFeedback

      Course "1" -> "0..*" Exam

      ClosingEvent -> ExamGradingService
      note bottom: responsible for auto-correcting\nand grading the exam

      Student "1" -right-> "0..1" ExamResult
      Teacher "*" -u-> "1" ExamSpecification : creates >
  }

  package BOARDPackage <<Rectangle>> {
  package BOARD <<Aggregate>> {

      entity Board <<root>> <<Entity>>
      note right: criar a entidade que gere as celulas ou e a board\n que gere as celulas

      class BoardTitle <<value object>>

      class CreateBoard <<Event>>
  }

  package CELL <<Aggregate>> {
      entity Cell <<Entity>>{
              -header
          }

          class HistoryUpdate <<value object>> 

          entity PostIt <<Entity>> {
              - postItId
              - typeOfContent
          }
          note right: Image or text
  }

    Cell "1" --> "*" HistoryUpdate
    Board "1" --> "1" BoardTitle
    Board "1" *-up- "1..*" Cell : part of <
    Cell "1"  *--- "0..1" PostIt : part of <

    CreateBoard -> Board

    Student "1" -up--> "*" Board : creates >
    Teacher "1" -up--> "*" Board : creates >
    Manager "1" -> "*" Board : creates >

  }

  package MEETING <<Aggregate>> {

      entity Meeting <<root>> <<Entity>>

      class MeetingInfo <<value object>>{
          -admin
      }

      class Time <<value object>> 

      class Duration <<value object>> 

      class ScheduleMeeting <<Event>>

      class AcceptMeeting <<Event>>

      class RejectMeeting <<Event>>

      class CancelsMeeting <<Event>>

      Meeting "1" --> "1" Time
      Meeting "1" --> "1" Duration
      Meeting "1" --> "1" MeetingInfo
      Meeting "1" -up-> "1" ScheduleMeeting
      CancelsMeeting "1" -down-> "1" Meeting
      AcceptMeeting "1" -down-> "1" Meeting
      RejectMeeting "1" -down-> "1" Meeting

      Student "1" -> "*" Meeting : creates/participate >
      Teacher "1" -> "*" Meeting : creates/participate  >
      Manager "1" -> "*" Meeting : creates/participate >

      Meeting -up|> Event
  }


  class UserManagementService <<Service>>
  Manager --left> UserManagementService
  note left: responsible for creating, disabling/enabling, \nand listing users in the system

  class CourseManagementService <<Service>>
  Course -> CourseManagementService
  note right: responsible for enrolling students in a course,\n either by bulk import or by individual request

  class SharedBoardService <<Service>>
  Board -down--> SharedBoardService
  note right :responsible for creating,\n sharing, and managing\n shared boards and post-its

  class MeetingService <<Service>>
  Meeting -> MeetingService
  note right :responsible for managing\n meetings between users
@enduml
