@startuml
'https://plantuml.com/state-diagram

skinparam linetype ortho
skinparam Shadowing False
scale 350 width




state State_Close
state State_Open
state State_Enroll
state State_In_Progress


[*] ---> State_Close : event create
State_Close --> State_Open : event open
State_Open --> State_Enroll: event open enrollments
State_Enroll --> State_In_Progress : event close enrollments
State_In_Progress --> State_Close : event close

State_Close --> [*]

'state
@enduml