@startuml

skinparam linetype ortho
skinparam Shadowing False

skinparam class {
    BackgroundColor<<Entity>> Moccasin
    BackgroundColor<<value object>> Azure
    BackgroundColor<<Event>> MediumAquaMarine
    BackgroundColor<<Service>> SkyBlue
    ArrowColor DarkSlateGrey
}

skinparam package {
    BackgroundColor PowderBlue
    packageLayout grid
    packageColumn 2
}


package UserPackage <<Rectangle>>{

    package SystemUser <<Aggregate>> {
        Class SystemUser <<Entity>>
        class Password <<value object>>
        class Email <<value object>>
        
        SystemUser -> Password
        SystemUser -> Email
    }


    package TEACHER <<Aggregate>> {
        entity Teacher <<root>> <<Entity>>{
            - FullName
            - ShortName
            - DateOfBirth
            - TaxPayerNumber
        }
        class Acronym <<value object>>

        Teacher  ->  Acronym
    }

    package MANAGER <<Aggregate>> {
        entity Manager <<root>> <<Entity>>{
            - FullName
            - ShortName
            - DateOfBirth
            - TaxPayerNumber


        }
        class ManagerId <<value object>>

        Manager  ->  ManagerId
    }


    package STUDENT <<Aggregate>> {
        entity Student <<root>> <<Entity>>{
            - FullName
            - ShortName
            - DateOfBirth
            - TaxPayerNumber
        }
        class MecanographicNumber <<value object>>

        Student  ->  MecanographicNumber
    }

    SystemUser -down-> "0..1" Manager    
    SystemUser -down-> "0..1" Teacher
    SystemUser -down-> "0..1" Student
}

package CoursePackage <<Rectangle>> {
    package COURSE <<Aggregate>> {
        entity Course <<root>> <<Entity>>

        class CourseCode <<value object>>

        class CourseName <<value object>>

        class CourseDescription <<value object>>

        class CourseDuration <<value object>>{
            - startDate
            - endDate
        }

        enum CourseState <<enum>>{
            - closed
            - open
            - enroll
            - inProgress
        }

        class CourseCapacity <<value object>> {
            -minStudents
            -maxStudents
        }

        abstract CourseEvent <<Event>>

        class CourseClosedEvent <<Event>>
        class CourseOpenEvent <<Event>>
        class CourseEnrollOpenEvent <<Event>>
        class CourseEnrollClosedEvent <<Event>>
        class CourseCreatedEvent <<Event>>

        Course  -down-> CourseCode
        Course  -up-> CourseName
        Course  -up->  CourseState
        Course  -down->  CourseDescription
        Course  -down-> CourseCapacity
        Course -up-> CourseEvent
        Course "1" ----> "*" Lecture
        Course -> CourseDuration

        CourseEvent <|-up-- CourseClosedEvent
        CourseEvent <|-left-- CourseOpenEvent
        CourseEvent <|-up-- CourseEnrollOpenEvent
        CourseEvent <|-up-- CourseEnrollClosedEvent
        CourseEvent <|-up-- CourseCreatedEvent

    }

    package STAFF <<Aggregate>>{
        entity Staff <<Entity>>
    }
    note right : STAFFF?????? \\0/ change name
    Course -down--> Staff

    package COURSE_ACCESS <<Aggregate>>{
        entity Enrollment <<root>> <<Entity>>
    }
    Student "*" <-- "1" Enrollment

    package COURSE_ENROLLMENT_REQUEST <<Aggregate>>{

        entity EnrollmentRequest <<root>> <<Entity>>
        entity DeniedReason <<value object>>

        enum RequestState <<enum>>{
            - approved
            - denied
            - pending
        }

        EnrollmentRequest "1" -> "0..1"DeniedReason
        EnrollmentRequest -> RequestState
        EnrollmentRequest  o-- "*" Student
        EnrollmentRequest --> Course        
    }

    Teacher "*" -up--o "1" Staff 
    Teacher "1" <-up-- "0..*" Course : teacher in charge

    class CourseManagementService <<Service>>
    Course -> CourseManagementService
    note top: responsible for enrolling students in a course,\n either by bulk import or by individual request

    Course "1" *- "1" Enrollment 
}

package ExamPackage <<Rectangle>> {

    package REGULAR_EXAM <<Aggregate>> {
        entity RegularExam <<root>> <<Entity>>

        class ExamDate <<value object>> {
            -openDate
            -closeDate
        }

        class ClosingEvent <<Event>>

        class ExamTitle <<value object>>
        class HeaderDescription <<value object>>
        class ExamHeader <<value object>>

        enum FeedbackType <<value object>> {
            - none
            - onSubmission
            - afterClosing
        }

        enum GradeType <<value object>> {
            - none
            - onSubmission
            - afterClosing
        }

    }

'code duplied??? 
'both types of exams need to have the exameSection-> 
'this exam section should store the questions for that exame(??)

    class ExamSection <<value object>>{
        - description
    }
    class ExamQuestion <<entity>>
    class QuestionWeight<<value object>>
    
    ExamSection *- "*"ExamQuestion
    ExamQuestion <- QuestionWeight

    package FORMATIVE_EXAM <<Aggregate>> {
        entity FormativeExam <<root>> <<entity>>
        note right: feedback and grading are always on submission
    }

    package FORMATIVE_EXAM_SPECIFICATION <<Aggregate>> {
        entity FormativeExamSpecification <<root>> <<entity>>

        class FormativeExamTitle <<value object>>
        class FormativeExamDescription <<value object>>
        class FormativeExamSection <<value object>>{
            - description
        }
    }

    package QUESTION <<Aggregate>> {
        entity Question <<root>> <<entity>> {
            -description
            -solution
        }

        class QuestionFeedback <<value object>>

        enum QuestionType <<enum>> {
            - matching
            - multipleChoices
            - shortAnswer
            - numerical
            - selectMissingWord
            - true/False
        }

    }

    package EXAM_RESULT <<Aggregate>> {
        entity ExamResult <<root>> <<Entity>>{
            - period
        }
        class ExamGrade <<value object>>
        class ExamFeedback <<value object>>
        
        entity AnswerGiven <<root>> <<Entity>>{
        }

    }

    class Answer <<value object>>{
    }

    class SubmissionEvent <<Event>>
    class ExamGradingService <<Service>>

    FormativeExamSpecification "1" --down-> "0..1" FormativeExamDescription
    FormativeExamSpecification  -->  FormativeExamTitle
    FormativeExamSpecification "1" -up-> "*" FormativeExamSection
    FormativeExamSpecification "1" -up---> "0..*" FormativeExam

    ExamHeader "1" -right--> "0..1" HeaderDescription
    ExamHeader -down-> FeedbackType
    ExamHeader -down-> GradeType


    RegularExam -up-> ExamTitle
    RegularExam  -down--> ExamHeader
    RegularExam  -up-> "1..*" ExamSection
    FormativeExam --> "1..*" ExamSection

    ExamSection -up--> "1..*" Question

    Question  -up-> Answer : solution
    Question  -up-> QuestionType
    Question -> "0..*" QuestionFeedback

    QuestionType "1..*" <--- "1" FormativeExamSection

    RegularExam -> ExamDate

    /' curso liga se a exame '/

    ClosingEvent <-up-- RegularExam
    SubmissionEvent -> ExamGradingService
    RegularExam --> SubmissionEvent
    FormativeExam --> SubmissionEvent

    ExamGradingService "1" ---up--> "1" ExamResult

    ExamResult -up-> ExamGrade
    ExamResult -> ExamFeedback
    ExamResult  -right-> Student :does exam <

    ExamResult *- "*" AnswerGiven
    AnswerGiven -->  Question 
    AnswerGiven -> Answer

    Course *-- "0..*" RegularExam
    Course *-- "0..*" FormativeExam

    ClosingEvent -> ExamGradingService
    note bottom: responsible for auto-correcting\nand grading the exam

    Teacher -->  RegularExam
}

package BoardPackage <<Rectangle>> {
    package BOARD <<Aggregate>> {

        entity Board <<root>> <<Entity>>{
            - MaxCollumns
            - MaxRows
        }
        class BoardTitle <<value object>>

        enum BoardStatus <<enum>>{
            - created
            - shared
            - archived
        }

        entity BoardRow <<Entity>>{
            - rowId
            - rowTitle          
        }
                
        entity BoardCollumn  <<Entity>>{
            - collumnId
            - collumnTitle
        }
        
        entity Cell <<Entity>>{
        }
        class Header<<value object>>
        
        entity BoardHistory <<Entity>>
        note left : stores every post-it that \nis created/modified

        class TimeStamp <<value object>>

        entity PostIt <<Entity>> {
            - postItId
        }
        note right: Image or text

        enum TypeOfContent <<enum>>{
            - text
            - image
        }

        entity  BoardParticipant <<Entity>>
        
        enum Permissions <<enum>>{
            - read
            - write
        }

        class ShareBoardEvent <<Event>>

        class CommitPostItEvent <<Event>>
        note bottom : event triggered when\npost-it is created or modified

        class ShareBoardService <<Service>>
        Board --> ShareBoardService
        note right :responsible for sharing boards

        class PostItService <<Service>>
        BoardHistory ---> PostItService
        note bottom : responsible for create or modify PostIt\n(save previous post in BoardHistory)

        class CreateBoardService <<Service>>
        Board  -up-> CreateBoardService
        note bottom : responsible manage the cells in the board



    }

    Board *-up- "*" BoardRow
    Board *-up- "*" BoardCollumn
    Board --> BoardStatus
    Board --> BoardTitle
    Board --> "*" BoardHistory
    Board *--> "1..*" Cell
    Board <-- SystemUser : admin

    Cell "1" o-- "0..1" PostIt     
    Cell -left> Header
    Cell -> BoardCollumn
    Cell -> BoardRow

    ShareBoardEvent <- Board
    ShareBoardEvent --> ShareBoardService

    BoardParticipant "*" --* Board
    BoardParticipant o-- "*"  SystemUser
    BoardParticipant -->  Permissions

    PostIt --> BoardParticipant : owns <
    PostIt --> TypeOfContent

    CommitPostItEvent <- PostIt
    CommitPostItEvent ---> PostItService

    BoardHistory -> TimeStamp
    BoardHistory --> PostIt
    BoardHistory "1" --> "1" BoardParticipant : commits post-it <

}

package EventPackage <<Rectangle>> {

  

    package TIMETABLE <<Aggregate>> {

        entity Timetable <<root>> <<entity>>{
        }
        note right : event access, timetable stores\nN RecurringPattern or 1(?)\nfor each user

        Timetable "*" o- "1" SystemUser 

    }

    package EVENT <<Aggregate>> {

        entity Event <<root>> <<entity>>{

        }
        class Exception{
            -period
        }
        note right:????

        class RescheduleEventService <<Service>>
        Exception --> RescheduleEventService

        entity RecurringPattern <<entity>>{
            -endDate
            -startDate
            -dayOfTheWeek
            -startTime
            -endTime
        }
        class RescheduleEventService <<Service>>

        enum RecurringFrequency <<enum>>{
            - weekly
            - once
        }

        RecurringPattern --> RecurringFrequency
    }

    class CheckAvailabilityService<<Service>>

    package Lecture <<Aggregate>>{
        entity Lecture <<root>> <<entity>> {
        }
        enum LectureType {
            -regular
            -extra
        }

        entity LectureParticipant <<entity>> {

        }

        Lecture --> LectureType
    }


    package MEETING <<Aggregate>> {

        entity Meeting <<root>> <<Entity>>

        class ScheduleMeetingEvent <<Event>>

        class CancelsMeetingEvent <<Event>>

        class MeetingService <<Service>>
        note right: responsible for managing\n meetings between users

        entity MeetingParticipant <<Entity>>

        enum ParticipantStatus {
            - accepted
            - rejected
            - pending
        }

        Meeting -> MeetingService
        Meeting  -up->  ScheduleMeetingEvent
        Meeting <-up- CancelsMeetingEvent

        MeetingParticipant "1" -> "*" SystemUser
        MeetingParticipant  ->  ParticipantStatus
        MeetingParticipant "*" --up> "1" Meeting

    }

    Timetable --> CheckAvailabilityService
    Timetable "1..*" -* "1" RecurringPattern

    RecurringPattern --> CheckAvailabilityService
    RecurringPattern "1" *-- "*" Exception

    Event "1" *-down- "*" RecurringPattern

    Lecture "1" o-- "1" Teacher : teaches
    Lecture -down--> Event
    Lecture "1" *- "1..*" LectureParticipant
    LectureParticipant o-- Student


    Meeting  ->  SystemUser : administrates
    Meeting -down-> Event
}

@enduml
