@startuml
actor Client as client
actor Server as server


'client -> server: shareBoardsOwned(user)
'client <-- server: boardsOwned
'client -> server: chooseBoard(board)
'client <-- server: usersNotInvited
'client -> server: inviteUsers(users)
'client <-- server: sends ACK code


client -> server : listBoardsUserOwnsNotArchived(owner)
client <-- server :boardsOwnedNotArchived
client -> server : archivedBoards(board)
note right :archives the board\n,sent back the list of\nboards in archived state
client <-- server : boardsArchived
@enduml