@startuml
actor Student as student
participant TakeExamUI as ui
participant TakeExamController as ctrl

participant RegularExamRepository as exam_repo

participant ParseExamServiceFactory as parser_factory
participant ParseExamService as parser_svc

participant ExamToBeTakenDTO as taken_dto

student --> ui : chooses exam
activate ui
    ui --> ctrl : examToBeTaken(examDTO)
    activate ctrl
        ctrl --> exam_repo : ofIdentity()
        activate exam_repo
            exam_repo --> ctrl : exam
        deactivate exam_repo

        ctrl --> parser_factory : examParserService()
        activate parser_factory
            note right: parser service obtained via \nproperties file
        deactivate parser_factory

        ctrl --> parser_svc : generateExam(exam)
        activate parser_svc
            note right: exam generation done \nby an external service
            parser_svc --> taken_dto : create()
            activate taken_dto
            deactivate taken_dto
            parser_svc --> ctrl : takenDTO
        deactivate parser_svc
        ctrl --> ui : takenDTO
    deactivate ctrl
    ui --> student : present exam
deactivate ui
@enduml