@startuml
class LoginUI <<presentation>>
class AuthenticationService <<application>>
class UserSession <<domain>>
class Role <<value object>>

AuthenticationService : create(role,maxAttempts)
LoginUI --> AuthenticationService : authentication
note right: Service developed by: \neapli.base.framework
AuthenticationService : autenticate(E-Mail, Password, onlyWithThis)
LoginUI ..> Role : role
AuthenticationService --> UserSession : theSession

LoginUI : show()
@enduml